name: Test ci folder
on: [push]

jobs:
  npm_test:
    name: Run npm tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4

    - name: Install D compiler
      uses: dlang-community/setup-dlang@v2
      with:
        compiler: dmd

    - name: Start xvfb
      if: startsWith(matrix.os, 'ubuntu')
      run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

    - name: Set Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: npm install
      run: npm install

    - name: typescript
      run: npx tsc

    - name: npm test
      env:
        CODE_VERSION: ''
        DISPLAY: ':99.0'
      run: npm test

    - name: test grammar
      if: startsWith(matrix.os, 'ubuntu')
      run: npm run grammar
